### ISSUE TITLE
swap between YASHE and e.g. JSON

### ISSUE THREAD

**Issue by ericprud** [weso/YASHE#186]
I want to use YASHE in [shex-simple](http://shex.io/webapps/shex.js/doc/shex-simple) but the ShExC input area is also used for ShExJ and ShExR (maybe soon YAML -- ShExY). I found a [CodeMirror demo that switches](https://codemirror.net/5/demo/changemode.html) using ```editor.setOption("mode", MODE)```, but YASHE doesn't give me back the cm object (it's in a closure).

Have you played with this?

**Comment by mistermboy** [comment]
Hey Eric, sorry for the late response. So glad to hear that you want to use YASHE!!! :smiley: :tada:

I've created [this pen](https://codepen.io/mistermboy/pen/vYaKKwa?editors=1010) as example for swapping between ShEx and JS.
It was not working for me at the beginning as I was defining the JavaScript mode using the Codemirror Object instead of the YASHE object. Maybe that's also your problem.

Let me know if you are able to make it work.

**Comment by ericprud** [comment]
... and *i'm* sorry for *my* late response. The codepen is great. I'm hoping to switch before the ShEx F2F on 11-12 Feb but I've got a lot of other stuff to prepare for the F2F so we'll see.
